import AboutMe from "@/components/AboutMe";
import Contact from "@/components/Contact";
import ExperienceCard from "@/components/Experiencia";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import NavBar from "@/components/NavBar";
import ProjectsSection from "@/components/Projects";
import Services from "@/components/Services";
import Technologies from "@/components/Technologies";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sebastian Burgos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link  rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <NavBar />
        <Hero />
        <AboutMe />
        <ExperienceCard/>
        <ProjectsSection />
        <Services />
        <Technologies />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
